# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_name', models.CharField(max_length=30)),
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admission_number', models.CharField(max_length=30)),
                ('class_id', models.IntegerField()),
            ],
        ),
    ]
