# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='admission_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
