# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180312_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='subject',
            field=models.TextField(default=b'I'),
        ),
    ]
