# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('department', models.CharField(max_length=30)),
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('section', models.CharField(max_length=2)),
                ('staff_advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Staff')),
            ],
        ),
    ]
