# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='staff_advisor',
            new_name='staff',
        ),
    ]
