# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20180225_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('hour1', models.IntegerField()),
                ('hour2', models.IntegerField()),
                ('hour3', models.IntegerField()),
                ('hour4', models.IntegerField()),
                ('hour5', models.IntegerField()),
                ('hour6', models.IntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Classroom')),
            ],
        ),
    ]
