# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-25 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20180225_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='hour1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.Subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='hour2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.Subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='hour3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.Subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='hour4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.Subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='hour5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.Subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='hour6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='timetable.Subject'),
        ),
    ]
