# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20180225_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='slug',
            field=models.CharField(default='CS8', max_length=50),
        ),
    ]
