# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Count',
            new_name='Counting',
        ),
    ]
