# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20180226_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
