# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20180227_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='subject',
        ),
    ]
