# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20180225_1923'),
        ('attendance', '0006_remove_record_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='hour1',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour2',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour3',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour4',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour5',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hour6',
        ),
        migrations.AddField(
            model_name='record',
            name='hour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='timetable.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
