# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20180227_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='date',
            new_name='date_time',
        ),
    ]
