# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_students'),
        ('attendance', '0012_auto_20180227_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('error_hrs', models.CharField(max_length=10)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Students')),
            ],
        ),
    ]
