# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20180227_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record1',
            name='hour1',
            field=models.CharField(default=b'absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='record1',
            name='hour2',
            field=models.CharField(default=b'absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='record1',
            name='hour3',
            field=models.CharField(default=b'absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='record1',
            name='hour4',
            field=models.CharField(default=b'absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='record1',
            name='hour5',
            field=models.CharField(default=b'absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='record1',
            name='hour6',
            field=models.CharField(default=b'absent', max_length=10),
        ),
    ]
